- src/pages/ProductDetailsPage.js
- src/pages/ProductsPage.js
- src/translations/en.json
https://openimis.atlassian.net/browse/OP-1016
This PR adds and displays labels when creating, updating and deleting a product.
> OP-1016: fix notifications about mutations

- src/utils.js
https://openimis.atlassian.net/browse/OP-1198
> OP-1198: The sum of relative pricing for all periods is not necessarily 100%

- src/components/ProductForm/GenericItemsTabForm.js
- src/constants.js
- src/utils.js
https://openimis.atlassian.net/browse/OTC-766
I encountered a problem with saving when editing items or services while working on a different ticket. Now it works fine.
> OP-987: fix canSave method

- src/components/ProductForm/GenericItemsTabForm.js
- src/utils.js
Ticket:
https://openimis.atlassian.net/browse/OTC-906
Changes:
- now all of the numbers are converted from integer to decimal and from NaN to 0
> OTC-906: converting integer into decimal limit number

- src/actions.js
- src/components/ProductForm/DeductiblesCeilingsTabForm.js
- src/components/ProductForm/TabsForm.js
- src/constants.js
- src/pickers/ProductPicker.js
- src/utils.js
TIcket:
https://openimis.atlassian.net/browse/OTC-899
Changes:
- code value is being passed to the backend
Related:
https://github.com/openimis/openimis-be-product_py/pull/27
Notes:
Before it was passed as null or uuid value
> Feature/otc 899: pass code value to backend

- src/components/ProductForm/DeductiblesCeilingsTabForm.js
- src/components/ProductForm/MainPanelForm.js
[OTC-902](https://openimis.atlassian.net/browse/OTC-902)
In scope of this ticket, I added the readOnly prop to the NumberInput as well as to the ValidatedTextInput.
[OTC-902]: https://openimis.atlassian.net/browse/OTC-902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OTC-902: Missing readOnly prop

- src/components/ProductForm/DeductiblesCeilingsTabForm.js
- src/components/ProductForm/GenericItemsTabForm.js
- src/components/ProductForm/MainPanelForm.js
- src/constants.js
- src/utils.js
https://openimis.atlassian.net/browse/OTC-938
This PR changes displaying of values in product according to description in above ticket.
> OTC-938: update displaying values in product

- src/components/ProductForm/MainPanelForm.js
Ticket:
https://openimis.atlassian.net/browse/OTC-905
Changes:
- disabled picking date from the past
> OTC-905: disabled picking past date in product form

- src/components/ProductForm/ProductForm.js
https://openimis.atlassian.net/browse/OTC-966
> OTC-966: make save button always visible

- src/components/ProductForm/ItemsTabForm.js
- src/components/ProductForm/MainPanelForm.js
- src/components/ProductForm/ProductForm.js
- src/components/ProductForm/ServicesTabForm.js
- src/components/ProductSearcher.js
- src/hooks.js
- src/index.js
- src/pages/ProductDetailsPage.js
- src/pages/ProductsPage.js
- src/translations/en.json
- src/utils.js
[BE PR](https://github.com/openimis/openimis-be-product_py/pull/28) REQUIRED
[OTC-856](https://openimis.atlassian.net/browse/OTC-856)
Changes:
- Addition of new duplication routes as well as the new mutation which duplicates a product.
- Only authorized users can duplicate a product.
- Implementation of "duplicate" button.
- When user enters a duplication form, code field is cleared and user is focused on it instantly.
- Addition of new keys to the Lokalise.
[OTC-856]: https://openimis.atlassian.net/browse/OTC-856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OTC-856: Duplication of an insurance product

- src/pages/ProductsPage.js
[OTC-856](https://openimis.atlassian.net/browse/OTC-856)
Changes:
- Missing import added.
[OTC-856]: https://openimis.atlassian.net/browse/OTC-856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OTC-856: Missing right import

- src/components/ProductForm/GenericItemsTabForm.js
- src/components/ProductForm/ItemsTabForm.js
- src/components/ProductForm/ServicesTabForm.js
- src/constants.js
https://openimis.atlassian.net/browse/OTC-1032
This PR changes default values in item/service product and prevent from submitting a negative value.
> OTC-1032: make no adult/child blank and prevent from submitting negative values

- src/components/ProductForm/GenericItemsTabForm.js
https://openimis.atlassian.net/browse/OP-1375
This PR allows to save a number in no_adult/no_child field.
> OP-1375: allow no adult and no child to save

- src/components/ProductForm/MainPanelForm.js
- src/components/ProductForm/ProductForm.js
- src/components/ProductSearcher.js
- src/pages/ProductDetailsPage.js
**[PR MERGE](https://github.com/openimis/openimis-fe_js/pull/80) REQUIRED**
[OTC-856](https://openimis.atlassian.net/browse/OTC-856)
Changes:
- User is allowed to modify "Date From" date.
- Ensure that the buttons remain in a horizontal orientation regardless of screen size or window width.
[OTC-856]: https://openimis.atlassian.net/browse/OTC-856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OTC-856: enable Date From modification

- src/utils.js
TIcket:
https://openimis.atlassian.net/browse/OTC-1064
Changes:
- Payment Grace Period default value set to 0
> OTC-1064: default value set to 0

- src/components/ProductFilters.js
https://openimis.atlassian.net/browse/OP-1366
This PR just changes placement of show history checkbox.
> OP-1366: change placement of show historical

- src/components/ProductForm/DataGrid.js
- src/components/ProductForm/GenericItemsTabForm.js
- src/components/ProductForm/ItemsTabForm.js
- src/components/ProductForm/ProductForm.js
- src/components/ProductForm/ServicesTabForm.js
https://openimis.atlassian.net/browse/OP-1443
This PR will not allow to edit product if is a historical instance.
> OP-1443: dont't let edit when historical values

- src/components/ProductForm/DataGrid.js
- src/components/ProductForm/GenericItemsTabForm.js
- src/components/ProductForm/ItemsTabForm.js
- src/components/ProductForm/ProductForm.js
- src/components/ProductForm/ServicesTabForm.js
- src/pickers/ProductPicker.js
MERGING RELEASE branches
Release release/23.04
> MERGING RELEASE branches

- src/constants.js
- src/pickers/ProductPicker.js
- src/translations/en.json
**[FE CORE PR](https://github.com/openimis/openimis-fe-core_js/pull/118) REQUIRED**
[OTC-1037](https://openimis.atlassian.net/browse/OTC-1037)
Changes:
- Show tooltip if product dropdown exceeds the limit of maximum products to display.
- New Lokalise key has been added.
[OTC-1037]: https://openimis.atlassian.net/browse/OTC-1037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OTC-1037: Show tooltip if product limit is exceeded

- src/components/ProductForm/DataGrid.js
- src/components/ProductForm/GenericItemsTabForm.js
- src/components/ProductForm/ItemsTabForm.js
- src/components/ProductForm/ProductForm.js
- src/pages/ProductDetailsPage.js
- src/utils.js
[OP-1443](https://openimis.atlassian.net/browse/OP-1443)
Changes:
- Saving/editing a historical product not possible (including medical items/services).
- LockedPage styles implemented when user is overviewing historical content.
[OP-1443]: https://openimis.atlassian.net/browse/OP-1443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1443: Block saving/editing historical product

- src/components/ProductFilters.js
[OTC-1096](https://openimis.atlassian.net/browse/OTC-1096)
Changes:
- The functionality for clearing the search criterias when clicking "Reset" button fixed.
[OTC-1096]: https://openimis.atlassian.net/browse/OTC-1096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OTC-1096: fix resetting search criteria  in product module

- src/index.js
- src/reports/ProductSalesReport.js
- src/translations/en.json
Product Sales report - FE
---
[Ticket](https://openimis.atlassian.net/jira/software/c/projects/OMT/issues/OMT-329)
[BE PR](https://github.com/openimis/openimis-be-product_py/pull/39)
> OMT-329 - Product Sales report

- src/components/ProductForm/DataGrid.js
- src/components/ProductForm/GenericItemsTabForm.js
- src/constants.js
https://openimis.atlassian.net/browse/OP-1551
This PR allows to go above 100 for fixed price for item or service in product.
> OP-1551: allow to go above 100 if fixed value

- src/utils.js
Ticket: https://openimis.atlassian.net/browse/ONI-181
Changes:
- Added new condition to canSave check.
- Now it allows Payment Grace Period to be equal to 0.
- This change was likely introduced in the generic core component.
> ONI-181: Changed canSave method to accomodate for possible 0 value.

- src/components/ProductForm/GenericItemsTabForm.js
- src/components/ProductForm/ItemsTabForm.js
- src/components/ProductForm/ServicesTabForm.js
- src/translations/en.json
[OP-1633](https://openimis.atlassian.net/browse/OP-1633)
Changes:
- Add possibility to customize add button's label.
[OP-1633]: https://openimis.atlassian.net/browse/OP-1633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1633: change labels on add buttons

- src/components/ProductForm/GenericItemsTabForm.js
- src/components/ProductForm/ItemsTabForm.js
- src/components/ProductForm/ServicesTabForm.js
- src/translations/en.json
- src/utils.js
MERGING RELEASE branches
Release release/23.10
> MERGING develop into release/23.10

- src/components/ProductForm/MainPanelForm.js
[OP-1591](https://openimis.atlassian.net/browse/OP-1591)
Changes:
- Fix date synchronization.
[OP-1591]: https://openimis.atlassian.net/browse/OP-1591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1591: fix date sync

- src/components/ProductForm/ContributionTabForm.js
- src/utils.js
[OP-1814](https://openimis.atlassian.net/browse/OP-1814)
https://github.com/openimis/openimis-fe-contribution_js/pull/42
https://github.com/openimis/openimis-fe-core_js/pull/205
Changes:
- Make 'maxInstallments' not required.
- Pass null if empty, pass 0 if 0 entered.
[OP-1814]: https://openimis.atlassian.net/browse/OP-1814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1814: make maxinstallments optional
